// Code generated by "stringer -type AccountType -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_ACCOUNTTYPE_VIRTUAL-48]
	_ = x[RH_ACCOUNTTYPE_REAL-49]
	_ = x[RH_ACCOUNTTYPE_REALGROUP-50]
}

const _AccountType_name = "虚拟账户真实账户资金账户组"

var _AccountType_index = [...]uint8{0, 12, 24, 39}

func (i AccountType) String() string {
	i -= 48
	if i >= AccountType(len(_AccountType_index)-1) {
		return "AccountType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
