// Code generated by "stringer -type BusinessType -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_BZTP_Future-49]
	_ = x[RH_TRADE_BZTP_Stock-50]
}

const _BusinessType_name = "期货证券"

var _BusinessType_index = [...]uint8{0, 6, 12}

func (i BusinessType) String() string {
	i -= 49
	if i >= BusinessType(len(_BusinessType_index)-1) {
		return "BusinessType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _BusinessType_name[_BusinessType_index[i]:_BusinessType_index[i+1]]
}
