// Code generated by "stringer -type CombinationType -linecomment"; DO NOT EDIT.

package rhmonitor4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CombFuture-48]
	_ = x[CombBull-49]
	_ = x[CombBear-50]
	_ = x[CombSTD-51]
	_ = x[CombSTG-52]
	_ = x[CombPRT-53]
	_ = x[CombCAS-54]
	_ = x[CombOPL-55]
	_ = x[CombBFO-56]
	_ = x[CombBLS-57]
	_ = x[CombBES-58]
}

const _CombinationType_name = "期货组合垂直价差牛市垂直价差熊市跨式组合款跨式组合备兑组合时间价差组合期权对锁组合买备兑组合买入期权垂直价差组合卖出期权垂直价差组合"

var _CombinationType_index = [...]uint8{0, 12, 30, 48, 60, 75, 87, 105, 123, 138, 168, 198}

func (i CombinationType) String() string {
	i -= 48
	if i >= CombinationType(len(_CombinationType_index)-1) {
		return "CombinationType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _CombinationType_name[_CombinationType_index[i]:_CombinationType_index[i+1]]
}
