// Code generated by "stringer -type Direction -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_D_Buy-48]
	_ = x[RH_TRADE_D_Sell-49]
}

const _Direction_name = "买卖"

var _Direction_index = [...]uint8{0, 3, 6}

func (i Direction) String() string {
	i -= 48
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
