// Code generated by "stringer -type ForceCloseReason -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_FCC_NotForceClose-48]
	_ = x[RH_TRADE_FCC_LackDeposit-49]
	_ = x[RH_TRADE_FCC_ClientOverPositionLimit-50]
	_ = x[RH_TRADE_FCC_MemberOverPositionLimit-51]
	_ = x[RH_TRADE_FCC_NotMultiple-52]
	_ = x[RH_TRADE_FCC_Violation-53]
	_ = x[RH_TRADE_FCC_Other-54]
	_ = x[RH_TRADE_FCC_PersonDeliv-55]
}

const _ForceCloseReason_name = "非强平资金不足客户超仓会员超仓持仓非整数倍违规其它自然人临近交割"

var _ForceCloseReason_index = [...]uint8{0, 9, 21, 33, 45, 63, 69, 75, 96}

func (i ForceCloseReason) String() string {
	i -= 48
	if i >= ForceCloseReason(len(_ForceCloseReason_index)-1) {
		return "ForceCloseReason(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _ForceCloseReason_name[_ForceCloseReason_index[i]:_ForceCloseReason_index[i+1]]
}
