// Code generated by "stringer -type HedgeFlag -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_HF_Speculation-49]
	_ = x[RH_TRADE_HF_Arbitrage-50]
	_ = x[RH_TRADE_HF_Hedge-51]
	_ = x[RH_TRADE_HF_MarketMaker-53]
}

const (
	_HedgeFlag_name_0 = "投机套利套保"
	_HedgeFlag_name_1 = "做市商"
)

var (
	_HedgeFlag_index_0 = [...]uint8{0, 6, 12, 18}
)

func (i HedgeFlag) String() string {
	switch {
	case 49 <= i && i <= 51:
		i -= 49
		return _HedgeFlag_name_0[_HedgeFlag_index_0[i]:_HedgeFlag_index_0[i+1]]
	case i == 53:
		return _HedgeFlag_name_1
	default:
		return "HedgeFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
