// Code generated by "stringer -type InstLifePhase -linecomment"; DO NOT EDIT.

package rhmonitor4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotStart-48]
	_ = x[Started-49]
	_ = x[Pause-50]
	_ = x[Expired-51]
}

const _InstLifePhase_name = "未上市上市停牌到期"

var _InstLifePhase_index = [...]uint8{0, 9, 15, 21, 27}

func (i InstLifePhase) String() string {
	i -= 48
	if i >= InstLifePhase(len(_InstLifePhase_index)-1) {
		return "InstLifePhase(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _InstLifePhase_name[_InstLifePhase_index[i]:_InstLifePhase_index[i+1]]
}
