// Code generated by "stringer -type OffsetFlag -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_OF_Open-48]
	_ = x[RH_TRADE_OF_Close-49]
	_ = x[RH_TRADE_OF_ForceClose-50]
	_ = x[RH_TRADE_OF_CloseToday-51]
	_ = x[RH_TRADE_OF_CloseYesterday-52]
	_ = x[RH_TRADE_OF_ForceOff-53]
	_ = x[RH_TRADE_OF_LocalForceClose-54]
}

const _OffsetFlag_name = "开仓平仓强平平今平昨强减本地强减"

var _OffsetFlag_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 48}

func (i OffsetFlag) String() string {
	i -= 48
	if i >= OffsetFlag(len(_OffsetFlag_index)-1) {
		return "OffsetFlag(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _OffsetFlag_name[_OffsetFlag_index[i]:_OffsetFlag_index[i+1]]
}
