// Code generated by "stringer -type OrderType -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_ORDT_Normal-48]
	_ = x[RH_TRADE_ORDT_DeriveFromQuote-49]
	_ = x[RH_TRADE_ORDT_DeriveFromCombination-50]
	_ = x[RH_TRADE_ORDT_Combination-51]
	_ = x[RH_TRADE_ORDT_ConditionalOrder-52]
	_ = x[RH_TRADE_ORDT_Swap-53]
	_ = x[RH_TRADE_ORDT_FinancingBuy-71]
	_ = x[RH_TRADE_ORDT_SellRepayMoney-72]
	_ = x[RH_TRADE_ORDT_FinancingSell-73]
	_ = x[RH_TRADE_ORDT_RepayStock-82]
}

const (
	_OrderType_name_0 = "正常报价衍生组合衍生组合报单条件单互换单"
	_OrderType_name_1 = "融资买入单卖券还款融资平仓"
	_OrderType_name_2 = "现券还券"
)

var (
	_OrderType_index_0 = [...]uint8{0, 6, 18, 30, 42, 51, 60}
	_OrderType_index_1 = [...]uint8{0, 15, 27, 39}
)

func (i OrderType) String() string {
	switch {
	case 48 <= i && i <= 53:
		i -= 48
		return _OrderType_name_0[_OrderType_index_0[i]:_OrderType_index_0[i+1]]
	case 71 <= i && i <= 73:
		i -= 71
		return _OrderType_name_1[_OrderType_index_1[i]:_OrderType_index_1[i+1]]
	case i == 82:
		return _OrderType_name_2
	default:
		return "OrderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
