// Code generated by "stringer -type PositionDateType -linecomment"; DO NOT EDIT.

package rhmonitor4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UseHistory-49]
	_ = x[NoUseHistory-50]
}

const _PositionDateType_name = "使用历史持仓不使用历史持仓"

var _PositionDateType_index = [...]uint8{0, 18, 39}

func (i PositionDateType) String() string {
	i -= 49
	if i >= PositionDateType(len(_PositionDateType_index)-1) {
		return "PositionDateType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _PositionDateType_name[_PositionDateType_index[i]:_PositionDateType_index[i+1]]
}
