// Code generated by "stringer -type PositionType -linecomment"; DO NOT EDIT.

package rhmonitor4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NetPosition-49]
	_ = x[GrossPosition-50]
}

const _PositionType_name = "净持仓综合持仓"

var _PositionType_index = [...]uint8{0, 9, 21}

func (i PositionType) String() string {
	i -= 49
	if i >= PositionType(len(_PositionType_index)-1) {
		return "PositionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _PositionType_name[_PositionType_index[i]:_PositionType_index[i+1]]
}
