// Code generated by "stringer -type PriceSource -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_PSRC_LastPrice-48]
	_ = x[RH_TRADE_PSRC_Buy-49]
	_ = x[RH_TRADE_PSRC_Sell-50]
}

const _PriceSource_name = "前成交价买委托价卖委托价"

var _PriceSource_index = [...]uint8{0, 12, 24, 36}

func (i PriceSource) String() string {
	i -= 48
	if i >= PriceSource(len(_PriceSource_index)-1) {
		return "PriceSource(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _PriceSource_name[_PriceSource_index[i]:_PriceSource_index[i+1]]
}
