// Code generated by "stringer -type SubInfoType -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RHMonitorSubPushInfoType_Order-1]
	_ = x[RHMonitorSubPushInfoType_Trade-2]
}

const _SubInfoType_name = "委托回报成交回报"

var _SubInfoType_index = [...]uint8{0, 12, 24}

func (i SubInfoType) String() string {
	i -= 1
	if i < 0 || i >= SubInfoType(len(_SubInfoType_index)-1) {
		return "SubInfoType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SubInfoType_name[_SubInfoType_index[i]:_SubInfoType_index[i+1]]
}
