// Code generated by "stringer -type TradingRole -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_ER_Broker-49]
	_ = x[RH_TRADE_ER_Host-50]
	_ = x[RH_TRADE_ER_Maker-51]
}

const _TradingRole_name = "代理自营做市商"

var _TradingRole_index = [...]uint8{0, 6, 12, 21}

func (i TradingRole) String() string {
	i -= 49
	if i >= TradingRole(len(_TradingRole_index)-1) {
		return "TradingRole(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TradingRole_name[_TradingRole_index[i]:_TradingRole_index[i+1]]
}
