// Code generated by "stringer -type TradeSource -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TRH_TSRC_NORMAL-48]
	_ = x[TRH_TSRC_QUERY-49]
}

const _TradeSource_name = "来自交易所回报来自查询"

var _TradeSource_index = [...]uint8{0, 21, 33}

func (i TradeSource) String() string {
	i -= 48
	if i >= TradeSource(len(_TradeSource_index)-1) {
		return "TradeSource(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TradeSource_name[_TradeSource_index[i]:_TradeSource_index[i+1]]
}
