// Code generated by "stringer -type VolumeCondition -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_VC_AV-49]
	_ = x[RH_TRADE_VC_MV-50]
	_ = x[RH_TRADE_VC_CV-51]
}

const _VolumeCondition_name = "任何数量最小数量全部数量"

var _VolumeCondition_index = [...]uint8{0, 12, 24, 36}

func (i VolumeCondition) String() string {
	i -= 49
	if i >= VolumeCondition(len(_VolumeCondition_index)-1) {
		return "VolumeCondition(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _VolumeCondition_name[_VolumeCondition_index[i]:_VolumeCondition_index[i+1]]
}
