// Code generated by "stringer -type MsgFormat -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgProto3-0]
	_ = x[MsgJson-1]
	_ = x[MsgPack-2]
}

const _MsgFormat_name = "proto3jsonmsgpack"

var _MsgFormat_index = [...]uint8{0, 6, 10, 17}

func (i MsgFormat) String() string {
	if i >= MsgFormat(len(_MsgFormat_index)-1) {
		return "MsgFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgFormat_name[_MsgFormat_index[i]:_MsgFormat_index[i+1]]
}
